version: "3.3"
services:
    mysqldb:
        image: mysql/mysql-server:8.0
        volumes:
            - "./.data/mysqldb:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - 3306:3306
    API:
        image: 'user-1.jar'
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        depends_on:
          mysqldb:
            condition: service_healthy